Pateash/pytest coverage support v2
SimpleDataLabsInc/prophecy-build-tool pull request #85
Opened 2024-04-25 13:29 UTC by pateash

2024-05-25 04:28 UTC, kirankaranth approved these changes

2024-05-25 08:11 UTC, ashvjit-prophecy approved these changes

2024-05-29 17:17 UTC, neontty requested changes
my mistake; I installed the wrong whl when I pulled your branch to test

a unittest would be nice but not a blocker

2024-05-29 17:24 UTC, pateash commented
I am not sure about he setup for v2,
@pankajb23 could you please help here 🙏

2024-05-29 17:25 UTC, neontty approved these changes

2024-06-07 21:31 UTC, neontty commented
@pateash I added junitxml tests. can we please merge this branch and do the unittest for test-v2 later?

2024-06-08 04:35 UTC, merged